version: '3' # This is the docker compose version

services:                   #Defines the list of services that make up the application stack
  web:                      #Name of the service, in this case, web   
    build: .                #Tells Docker Compose to build the docker image for this service using the Dockerfile located in the current directory
    command: python manage.py runserver 0.0.0.0:8000   #This is the command that runs when the container starts - this is the Django development server command
    volumes:                #This command mounts the current dir into the container at the /code directory. -This allows changes made to code on the host machine to                   
      - ./tictactoe_server:/code             #be reflected in the container right away.
    ports:                  #This maps the container's port to the host's port.
      - "8000:8000"
    depends_on:             #Defines services this service depends on. These will start before this service does.
      - redis
      - celery

  
  celery:
    build: .
    command: celery -A tictactoe_server worker -l info
    volumes:
      - ./tictactoe_server:/code  
    depends_on:
      - redis

  celery-beat:
    build: .
    volumes:
      - ./tictactoe_server:/code
    working_dir: /code
    command: celery -A tictactoe_server beat --loglevel=info
      


  redis:
    image: redis:latest