# Generated by Django 5.0.4 on 2024-04-07 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_player', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
                ('current_team', models.CharField(max_length=100)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttt_player.opponent')),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='ttt_player.team')),
            ],
        ),
    ]
