# Generated by Django 5.0.4 on 2024-04-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_player', '0002_alter_team_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttt_player.opponent'),
        ),
    ]
