# Generated by Django 5.0.4 on 2024-04-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_player', '0003_alter_game_current_team_alter_game_opponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('column', models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='ttt_player.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttt_player.team')),
            ],
            options={
                'unique_together': {('game', 'row', 'column')},
            },
        ),
    ]
