# Generated by Django 5.0.4 on 2024-04-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_player', '0004_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='value',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
