# Generated by Django 5.0.4 on 2024-04-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_player', '0005_move_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_team',
            new_name='turn',
        ),
    ]
