# Generated by Django 5.0.4 on 2024-04-16 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_player', '0006_rename_current_team_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='Opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttt_player.opponent'),
        ),
        migrations.AlterField(
            model_name='move',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttt_player.team'),
        ),
    ]
