# Generated by Django 5.0.4 on 2024-04-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_player', '0007_move_opponent_alter_move_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='Opponent',
            new_name='opponent',
        ),
    ]
